import type {NextPage} from 'next';
import Head from 'next/head';

const IndexPage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/** TODO */}
        </div>
    );
};

export default IndexPage;
